### ISSUE TITLE
请问有中文版论文吗

### ISSUE THREAD

**Issue by baoqian426** [xgdsmileboy/SimFix#2]
请问有中文版论文吗

**Comment by xgdsmileboy** [comment]
不好意思，只有英文版论文的！

**Comment by xgdsmileboy** [comment]
你好。SimFix要求defects4j的目录应该满足下面的格式要求：
`$base/projectName/projectName_id_buggy`
传给SimFix的目录应该是`$base`,`projectName`以及`id`。你可以下载我们的replication package运行SimFix，已经配置好了环境信息。请参考最新的ReadMe。

**Comment by ziqiboyaMeng** [comment]
好的，我再看看，谢谢老师 发自我的华为手机-------- 原始邮件 --------主题：Re: [xgdsmileboy/SimFix] 请问有中文版论文吗 (#2)发件人：Jiajun Jiang 收件人：xgdsmileboy/SimFix 抄送：ziqiboyaMeng ,Comment 你好。SimFix要求defects4j的目录应该满足下面的格式要求：

$base/projectName/projectName_id_buggy

传给SimFix的目录应该是$base,projectName以及id。你可以下载我们的replication package运行SimFix，已经配置好了环境信息。请参考最新的ReadMe。



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xgdsmileboy/SimFix","title":"xgdsmileboy/SimFix","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xgdsmileboy/SimFix"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xgdsmileboy in #2: 你好。SimFix要求defects4j的目录应该满足下面的格式要求：\r\n`$base/projectName/projectName_id_buggy`\r\n传给SimFix的目录应该是`$base`,`projectName`以及`id`。你可以下载我们的replication package运行SimFix，已经配置好了环境信息。请参考最新的ReadMe。"}],"action":{"name":"View Issue","url":"https://github.com/xgdsmileboy/SimFix/issues/2#issuecomment-450462634"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/xgdsmileboy/SimFix/issues/2#issuecomment-450462634",

"url": "https://github.com/xgdsmileboy/SimFix/issues/2#issuecomment-450462634",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ziqiboyaMeng** [comment]
好的，谢谢老师，我再看一下

**Comment by ziqiboyaMeng** [comment]
老师，您好！我最近按照最新的readme文件中说到的那个replication package运行simfix，在  source source_me  后显示：Setting up project repositories...     init.sh: 行 30: ./get_repos.sh: 权限不够。我用root权限也运行了，但还是这样显示。请问您遇到过这种问题吗？这是我自己系统配置的原因吗？

**Comment by xgdsmileboy** [comment]
我们运行时没有出现这个问题，可能是系统问题？这个不是很清楚。我们的replication package 已经被至少除了我以外的5个其他人（有来自不同学校）使用过，都没有没有出现这个问题。大家都是正常运行的，所以我也不是很清楚。不好意思。

**Comment by ziqiboyaMeng** [comment]
好的，谢谢老师。那应该是我自己系统的原因，我再琢磨琢磨，谢谢老师。
