### ISSUE TITLE
Question about create a patch file

### ISSUE THREAD

**Issue by daleyli** [xgdsmileboy/SimFix#8]
Hi,

We have tried to run your tool on our side with Defects4J data set. For now, we can make the code run and we downloaded Defects4J data and buggy line information. But when using your code, there are always messages like "No block found!" and cannot create the patch file because it cannot find the buggy information.

The command we are using is "java -jar simfix.jar --proj_home=/home/user --proj_name=chart --bug_id=1". Is there any point we missed or could you please provide us some suggestions on this problem?

Thanks a lot.

**Comment by xgdsmileboy** [comment]
How about the running environment? Is it the same as required in the readme? Please have a double check. Additionally, you also can redirect the output into a file and check whether the correct patch is generated or not. According to my experience, most cases are due to the correctness validation process.
